version: "3"
services:
  web:
    depends_on:
      - redis
    build: .
    ports:
      - "5000:5000"
    environment:
      FLASK_ENV: "development"
      SENDGRID_API_KEY: <SENDGRID_API_KEY>
      DOMAIN_URL: http://127.0.0.1:5000
  redis:
    image: redis
    ports:
      - "6379:6379"
  nginx:
    depends_on:
      - web
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./nginx
    ports:
      - "3050:80"
